### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by ghost** [jb-aero/SKCompat#10]
Getting this error http://paste.yu8.me/?3de85a018fcee117#64rBkJ/1W426BlXWE92Qp33ljJ3jSdcaD2+ZDjY+FNE=

When trying to run it alongside command helper under my plugins folder

**Comment by jb-aero** [comment]
Because you put it in your plugins folder, instead of reading the description or any of the other things that should have lead you here.
