### ISSUE TITLE
Region_change not detecting movement between the same number of regions

### ISSUE THREAD

**Issue by Murreey** [jb-aero/SKCompat#23]
I updated my server, CH and extensions to 1.9, but it appears that CHWorldGuard no longer triggers when moving between areas with different regions, but the same number of total regions.

For example, if I have one large region with two smaller regions inside that are exactly next to each other, the event won't trigger when I move from the first smaller one to the second smaller one, but works fine between when leaving either of the smaller regions into just the bigger one.

Running build 28 of SKCompat (although I had to recompile for Java 7), with CHWorldGuard 1.1.0 build 21, and CommandHelper #3102.

(I looked for a specific issues page for CHWorldGuard, but was advised to post here)

Thanks!

**Comment by jb-aero** [comment]
region_change has not yet been added to SKCompat (it will be, and hopefully better).

**Comment by PseudoKnight** [comment]
I rewrote the code for version 1.1.0 and even tested that exact scenario. I'll retest it again.

I really don't like the idea of adding the event to sk_compat, at least not until you can add it to WG sessions, which is not yet possible. I wouldn't mind changing the extension's name, though.

**Comment by PseudoKnight** [comment]
Okay, I must have made a last minute change that messed this up. I'll fix it.

**Comment by PseudoKnight** [comment]
I fixed it and opened an issue tracker on my github for the project. Thanks for bringing this to my attention.

**Comment by Murreey** [comment]
Awesome, thanks!
