### ISSUE TITLE
skcb_paste java.lang.NoSuchFieldException: player with FastAsyncWorldEdit

### ISSUE THREAD

**Issue by PhanaticD** [jb-aero/SKCompat#26]
here is the error I get when trying to use skcb_paste http://hastebin.com/raw/oyujuqozeb

this is the plugin: https://github.com/boy0001/FastAsyncWorldedit

@boy0001 maybe you have input

**Comment by jb-aero** [comment]
Note to future self:
It appears FAWE expects a WorldEdit concept of Player, or an extension that contains a reference to one.

https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/boydti/fawe/object/FawePlayer.java#L82

**Comment by boy0001** [comment]
Fixed on my end
