### ISSUE TITLE
sk_region_owners giving incorrect names

### ISSUE THREAD

**Issue by PhanaticD** [jb-aero/SKCompat#7]
/test = msg(sk_region_owners(sk_current_regions()[0],pworld()))

^ this should give me all the region owners of the region I am currently standing in

however, this is the real region output using /rg info = http://gyazo.com/928a2881b64ab6dfe6a0639c08da49e8

and this is what commandhelper returns = {bubbr_x}

**Comment by jb-aero** [comment]
Dupe of #3
